version: '3'

services:

  openldap:
    # https://github.com/osixia/docker-openldap
    container_name: '${LDAP_CONTAINER_NAME}'
    image: osixia/openldap:${LDAP_OPENLDAP_VERSION}
    command: --loglevel debug
    user: '${RUN_UID}:${RUN_GID}'
    ports:
      - '${LDAP_PORT_UNSECURE}:389'
      - '${LDAP_PORT_SECURE}:636'
    environment:
      - LDAP_OPENLDAP_GID=${RUN_UID}
      - LDAP_OPENLDAP_UID=${RUN_GID}
      - LDAP_ORGANISATION=${LDAP_ORGANISATION}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD}
      - LDAP_READONLY_USER=${LDAP_READONLY_USER}
      - LDAP_READONLY_USER_USERNAME=${LDAP_READONLY_USER_USERNAME}
      - LDAP_READONLY_USER_PASSWORD=${LDAP_READONLY_USER_PASSWORD}
    volumes:
      - ${DATA_DIRECTORY}/${LDAP_CONTAINER_NAME}/data:/var/lib/ldap
      - ${DATA_DIRECTORY}/${LDAP_CONTAINER_NAME}/config:/etc/ldap/slapd.d
      - ${DATA_DIRECTORY}/${LDAP_CONTAINER_NAME}/certificates:/container/service/slapd/assets/certs

  mysql:
    # https://hub.docker.com/_/mysql
    container_name: '${MYSQL_CONTAINER_NAME}'
    image: mysql:${MYSQL_VERSION}
    user: '${RUN_UID}:${RUN_GID}'
    command: [ "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--require_secure_transport=ON",
                "--ssl-ca=/etc/certs/root-ca.pem",
                "--ssl-cert=/etc/certs/server-cert.pem",
                "--ssl-key=/etc/certs/server-key.pem" ]
    ports:
      - '${MYSQL_PROTOCOL_MYSQL_PORT}:3306'
      - '${MYSQL_PROTOCOL_MYSQLX_PORT}:33060'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d
      - ${DATA_DIRECTORY}/${MYSQL_CONTAINER_NAME}/data:/var/lib/mysql
      - ${DATA_DIRECTORY}/certs:/etc/certs

  mariadb:
    # https://hub.docker.com/_/mariadb
    container_name: '${MARIADB_CONTAINER_NAME}'
    image: mariadb:${MARIADB_VERSION}
    user: '${RUN_UID}:${RUN_GID}'
    command: [ "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
                "--ssl",
                "--ssl-ca=/etc/certs/root-ca.pem",
                "--ssl-cert=/etc/certs/server-cert.pem",
                "--ssl-key=/etc/certs/server-key.pem" ]
    ports:
      - '${MARIADB_PROTOCOL_MYSQL_PORT}:3306'
      - '${MARIADB_PROTOCOL_MYSQLX_PORT}:33060'
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./init/mariadb:/docker-entrypoint-initdb.d
      - ${DATA_DIRECTORY}/${MARIADB_CONTAINER_NAME}/data:/var/lib/mysql
      - ${DATA_DIRECTORY}/certs:/etc/certs

  postgres:
    # https://hub.docker.com/_/postgres
    container_name: '${POSTGRES_CONTAINER_NAME}'
    image: postgres:${POSTGRES_VERSION}
    user: '${RUN_UID}:${RUN_GID}'
    command: >
      -c ssl=on 
      -c ssl_cert_file=/etc/certs/server-cert.pem
      -c ssl_key_file=/etc/certs/server-key.pem
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
      - ${DATA_DIRECTORY}/${POSTGRES_CONTAINER_NAME}/data:/var/lib/postgresql/data
      - ${DATA_DIRECTORY}/certs:/etc/certs

  mssql:
    # https://hub.docker.com/_/microsoft-mssql-server
    container_name: '${MSSQL_CONTAINER_NAME}'
    image: 'mcr.microsoft.com/mssql/server:${MSSQL_VERSION}'
    user: root
    command: "/bin/bash /docker-entrypoint-initdb.d/entrypoint.sh"
    ports:
      - '${MSSQL_TCP_PORT}:1234'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=${MSSQL_TCP_PORT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - ./init/${MSSQL_CONTAINER_NAME}:/docker-entrypoint-initdb.d
      - ${DATA_DIRECTORY}/${MSSQL_CONTAINER_NAME}/data:/var/opt/mssql/data

  oracle:
    # https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/README.md
    container_name: '${ORACLE_CONTAINER_NAME}'
    image: 'oracle/database:${ORACLE_VERSION}'
    ports:
      - '${ORACLE_DB_PORT}:1521'
      - '${ORACLE_WEB_PORT}:5500'
    environment:
      - ORACLE_SID=${ORACLE_SID}
      - ORACLE_PDB=${ORACLE_PDB}
      - ORACLE_PWD=${ORACLE_PWD}
      - ORACLE_EDITION=${ORACLE_EDITION} 
      - ORACLE_CHARACTERSET=${ORACLE_CHARACTERSET}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    volumes:
      - ${DATA_DIRECTORY}/${ORACLE_CONTAINER_NAME}:/opt/oracle/oradata
      - ./init/${ORACLE_CONTAINER_NAME}/setup:/docker-entrypoint-initdb.d/setup
