-- Run SQL script against the PDB, not the default CDB
ALTER SESSION SET CONTAINER = "ORCLPDB1";
DROP TABLESPACE example INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP USER dbadmin CASCADE;
DROP USER dbuser1 CASCADE;
DROP USER dbuser2 CASCADE;
DROP USER dbuser3 CASCADE;
COMMIT;
